<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $categories = Category::pluck('id', 'name');
        $products = [
            [
                'name' => 'Wireless Bluetooth Headphones',
                'description' => 'Premium noise-cancelling headphones with 30-hour battery life and crystal clear sound quality.',
                'price' => 89.99,
                'original_price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
                'discount' => '30% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Smart Fitness Watch',
                'description' => 'Track your workouts, heart rate, and sleep patterns with this advanced fitness tracker.',
                'price' => 199.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Organic Cotton T-Shirt',
                'description' => 'Comfortable and sustainable cotton t-shirt available in multiple colors and sizes.',
                'price' => 24.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Stainless Steel Water Bottle',
                'description' => 'Keep your drinks cold for 24 hours or hot for 12 hours with this insulated bottle.',
                'price' => 34.99,
                'original_price' => 49.99,
                'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=300&fit=crop',
                'discount' => '30% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Portable Bluetooth Speaker',
                'description' => 'Waterproof speaker with 360-degree sound and 20-hour battery life for outdoor adventures.',
                'price' => 79.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Yoga Mat Premium',
                'description' => 'Non-slip yoga mat made from eco-friendly materials, perfect for home workouts.',
                'price' => 45.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => 'Coffee Maker Automatic',
                'description' => 'Programmable coffee maker with built-in grinder and thermal carafe for fresh coffee anytime.',
                'price' => 159.99,
                'original_price' => 199.99,
                'image' => 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400&h=300&fit=crop',
                'discount' => '20% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Wireless Charging Pad',
                'description' => 'Fast wireless charging pad compatible with all Qi-enabled devices, sleek design.',
                'price' => 29.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            // Additional products for pagination demonstration
            [
                'name' => 'Gaming Mouse RGB',
                'description' => 'High-precision gaming mouse with customizable RGB lighting and programmable buttons.',
                'price' => 59.99,
                'original_price' => 79.99,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
                'discount' => '25% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Denim Jeans Classic',
                'description' => 'Classic fit denim jeans with stretch comfort and timeless style.',
                'price' => 49.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Smart LED Bulbs Pack',
                'description' => 'WiFi-enabled smart LED bulbs with voice control and customizable colors.',
                'price' => 39.99,
                'original_price' => 59.99,
                'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop',
                'discount' => '33% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Running Shoes Pro',
                'description' => 'Professional running shoes with advanced cushioning and breathable mesh.',
                'price' => 129.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => 'Laptop Stand Adjustable',
                'description' => 'Ergonomic laptop stand with adjustable height and cooling ventilation.',
                'price' => 34.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Hoodie Fleece Comfort',
                'description' => 'Soft fleece hoodie perfect for casual wear and outdoor activities.',
                'price' => 39.99,
                'original_price' => 49.99,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=300&fit=crop',
                'discount' => '20% OFF',
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Garden Tool Set',
                'description' => 'Complete garden tool set with ergonomic handles and durable construction.',
                'price' => 89.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Basketball Official Size',
                'description' => 'Professional basketball with excellent grip and durability for indoor and outdoor play.',
                'price' => 29.99,
                'original_price' => 39.99,
                'image' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Sports'] ?? 4,
            ],
            // Additional products to reach 30 total
            [
                'name' => 'Wireless Gaming Headset',
                'description' => '7.1 surround sound gaming headset with noise-cancelling microphone and RGB lighting.',
                'price' => 79.99,
                'original_price' => 119.99,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
                'discount' => '33% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Smart Home Security Camera',
                'description' => '1080p HD security camera with night vision, motion detection, and mobile app control.',
                'price' => 89.99,
                'original_price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
                'discount' => '31% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Premium Cotton Hoodie',
                'description' => 'Soft cotton hoodie with kangaroo pocket and adjustable drawstring hood.',
                'price' => 45.99,
                'original_price' => 65.99,
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop',
                'discount' => '30% OFF',
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Smart LED Strip Lights',
                'description' => '16ft RGB LED strip with app control, voice commands, and music sync.',
                'price' => 34.99,
                'original_price' => 49.99,
                'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop',
                'discount' => '30% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Professional Tennis Racket',
                'description' => 'Carbon fiber tennis racket with excellent control and power for intermediate players.',
                'price' => 129.99,
                'original_price' => 179.99,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
                'discount' => '28% OFF',
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => 'Bluetooth Earbuds Pro',
                'description' => 'True wireless earbuds with active noise cancellation and 24-hour battery life.',
                'price' => 149.99,
                'original_price' => 199.99,
                'image' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=300&fit=crop',
                'discount' => '25% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Designer Denim Jacket',
                'description' => 'Classic denim jacket with modern fit and premium stitching details.',
                'price' => 89.99,
                'original_price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=300&fit=crop',
                'discount' => '31% OFF',
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Smart Plant Watering System',
                'description' => 'Automated plant watering system with soil sensors and mobile app monitoring.',
                'price' => 79.99,
                'original_price' => 99.99,
                'image' => 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop',
                'discount' => '20% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Professional Soccer Ball',
                'description' => 'FIFA approved soccer ball with premium leather and perfect roundness.',
                'price' => 49.99,
                'original_price' => 69.99,
                'image' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=300&fit=crop',
                'discount' => '29% OFF',
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => '4K Action Camera',
                'description' => 'Waterproof 4K action camera with image stabilization and 30fps recording.',
                'price' => 199.99,
                'original_price' => 299.99,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
                'discount' => '33% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Cashmere Sweater',
                'description' => 'Luxury cashmere sweater with ribbed texture and comfortable fit.',
                'price' => 129.99,
                'original_price' => 189.99,
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop',
                'discount' => '32% OFF',
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Smart Thermostat',
                'description' => 'WiFi-enabled smart thermostat with energy saving features and mobile control.',
                'price' => 149.99,
                'original_price' => 199.99,
                'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop',
                'discount' => '25% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Mountain Bike Helmet',
                'description' => 'Lightweight mountain bike helmet with MIPS protection and adjustable fit.',
                'price' => 89.99,
                'original_price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
                'discount' => '31% OFF',
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => 'Wireless Bluetooth Headphones',
                'description' => 'Premium noise-cancelling headphones with 30-hour battery life and crystal clear sound quality.',
                'price' => 89.99,
                'original_price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
                'discount' => '30% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Smart Fitness Watch',
                'description' => 'Track your workouts, heart rate, and sleep patterns with this advanced fitness tracker.',
                'price' => 199.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Organic Cotton T-Shirt',
                'description' => 'Comfortable and sustainable cotton t-shirt available in multiple colors and sizes.',
                'price' => 24.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Stainless Steel Water Bottle',
                'description' => 'Keep your drinks cold for 24 hours or hot for 12 hours with this insulated bottle.',
                'price' => 34.99,
                'original_price' => 49.99,
                'image' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=400&h=300&fit=crop',
                'discount' => '30% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Portable Bluetooth Speaker',
                'description' => 'Waterproof speaker with 360-degree sound and 20-hour battery life for outdoor adventures.',
                'price' => 79.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Yoga Mat Premium',
                'description' => 'Non-slip yoga mat made from eco-friendly materials, perfect for home workouts.',
                'price' => 45.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => 'Coffee Maker Automatic',
                'description' => 'Programmable coffee maker with built-in grinder and thermal carafe for fresh coffee anytime.',
                'price' => 159.99,
                'original_price' => 199.99,
                'image' => 'https://images.unsplash.com/photo-1517668808822-9ebb02f2a0e6?w=400&h=300&fit=crop',
                'discount' => '20% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Wireless Charging Pad',
                'description' => 'Fast wireless charging pad compatible with all Qi-enabled devices, sleek design.',
                'price' => 29.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1586953208448-b95a79798f07?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            // Additional products for pagination demonstration
            [
                'name' => 'Gaming Mouse RGB',
                'description' => 'High-precision gaming mouse with customizable RGB lighting and programmable buttons.',
                'price' => 59.99,
                'original_price' => 79.99,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
                'discount' => '25% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Denim Jeans Classic',
                'description' => 'Classic fit denim jeans with stretch comfort and timeless style.',
                'price' => 49.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Smart LED Bulbs Pack',
                'description' => 'WiFi-enabled smart LED bulbs with voice control and customizable colors.',
                'price' => 39.99,
                'original_price' => 59.99,
                'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop',
                'discount' => '33% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Running Shoes Pro',
                'description' => 'Professional running shoes with advanced cushioning and breathable mesh.',
                'price' => 129.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => 'Laptop Stand Adjustable',
                'description' => 'Ergonomic laptop stand with adjustable height and cooling ventilation.',
                'price' => 34.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Hoodie Fleece Comfort',
                'description' => 'Soft fleece hoodie perfect for casual wear and outdoor activities.',
                'price' => 39.99,
                'original_price' => 49.99,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=300&fit=crop',
                'discount' => '20% OFF',
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Garden Tool Set',
                'description' => 'Complete garden tool set with ergonomic handles and durable construction.',
                'price' => 89.99,
                'original_price' => null,
                'image' => 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Basketball Official Size',
                'description' => 'Professional basketball with excellent grip and durability for indoor and outdoor play.',
                'price' => 29.99,
                'original_price' => 39.99,
                'image' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=300&fit=crop',
                'discount' => null,
                'category_id' => $categories['Sports'] ?? 4,
            ],
            // Additional products to reach 30 total
            [
                'name' => 'Wireless Gaming Headset',
                'description' => '7.1 surround sound gaming headset with noise-cancelling microphone and RGB lighting.',
                'price' => 79.99,
                'original_price' => 119.99,
                'image' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=300&fit=crop',
                'discount' => '33% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Smart Home Security Camera',
                'description' => '1080p HD security camera with night vision, motion detection, and mobile app control.',
                'price' => 89.99,
                'original_price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
                'discount' => '31% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Premium Cotton Hoodie',
                'description' => 'Soft cotton hoodie with kangaroo pocket and adjustable drawstring hood.',
                'price' => 45.99,
                'original_price' => 65.99,
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop',
                'discount' => '30% OFF',
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Smart LED Strip Lights',
                'description' => '16ft RGB LED strip with app control, voice commands, and music sync.',
                'price' => 34.99,
                'original_price' => 49.99,
                'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop',
                'discount' => '30% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Professional Tennis Racket',
                'description' => 'Carbon fiber tennis racket with excellent control and power for intermediate players.',
                'price' => 129.99,
                'original_price' => 179.99,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
                'discount' => '28% OFF',
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => 'Bluetooth Earbuds Pro',
                'description' => 'True wireless earbuds with active noise cancellation and 24-hour battery life.',
                'price' => 149.99,
                'original_price' => 199.99,
                'image' => 'https://images.unsplash.com/photo-1588872657578-7efd1f1555ed?w=400&h=300&fit=crop',
                'discount' => '25% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Designer Denim Jacket',
                'description' => 'Classic denim jacket with modern fit and premium stitching details.',
                'price' => 89.99,
                'original_price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=400&h=300&fit=crop',
                'discount' => '31% OFF',
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Smart Plant Watering System',
                'description' => 'Automated plant watering system with soil sensors and mobile app monitoring.',
                'price' => 79.99,
                'original_price' => 99.99,
                'image' => 'https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=400&h=300&fit=crop',
                'discount' => '20% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Professional Soccer Ball',
                'description' => 'FIFA approved soccer ball with premium leather and perfect roundness.',
                'price' => 49.99,
                'original_price' => 69.99,
                'image' => 'https://images.unsplash.com/photo-1546519638-68e109498ffc?w=400&h=300&fit=crop',
                'discount' => '29% OFF',
                'category_id' => $categories['Sports'] ?? 4,
            ],
            [
                'name' => '4K Action Camera',
                'description' => 'Waterproof 4K action camera with image stabilization and 30fps recording.',
                'price' => 199.99,
                'original_price' => 299.99,
                'image' => 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=400&h=300&fit=crop',
                'discount' => '33% OFF',
                'category_id' => $categories['Electronics'] ?? 1,
            ],
            [
                'name' => 'Cashmere Sweater',
                'description' => 'Luxury cashmere sweater with ribbed texture and comfortable fit.',
                'price' => 129.99,
                'original_price' => 189.99,
                'image' => 'https://images.unsplash.com/photo-1542272604-787c3835535d?w=400&h=300&fit=crop',
                'discount' => '32% OFF',
                'category_id' => $categories['Clothing'] ?? 2,
            ],
            [
                'name' => 'Smart Thermostat',
                'description' => 'WiFi-enabled smart thermostat with energy saving features and mobile control.',
                'price' => 149.99,
                'original_price' => 199.99,
                'image' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=400&h=300&fit=crop',
                'discount' => '25% OFF',
                'category_id' => $categories['Home & Garden'] ?? 3,
            ],
            [
                'name' => 'Mountain Bike Helmet',
                'description' => 'Lightweight mountain bike helmet with MIPS protection and adjustable fit.',
                'price' => 89.99,
                'original_price' => 129.99,
                'image' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=300&fit=crop',
                'discount' => '31% OFF',
                'category_id' => $categories['Sports'] ?? 4,
            ],
        ];

        foreach ($products as $product) {
            Product::create($product);
        }
    }
}
